### ISSUE TITLE
egocentrism

### ISSUE THREAD

**Issue by ezeql** [Pallinder/go-randomdata#14]
List all https://github.com/Pallinder/go-randomdata/graphs/contributors in readme?

**Comment by Pallinder** [comment]
Will do.

**Comment by Pallinder** [comment]
If you want to feel free to come onboard and help me maintain it.

**Comment by ezeql** [comment]
surething!

**Comment by Pallinder** [comment]
Done.

**Comment by ezeql** [comment]
:+1:
