### ISSUE TITLE
make email more random

### ISSUE THREAD

**Issue by bubenkoff** [Pallinder/go-randomdata#23]
I'm currently using this package for test fixture generation
and it happens quite often that i get the same email in just few repetitive calls, which prevents from using it 'as is' and requiring to add some random part manually.

**Comment by Pallinder** [comment]
Do you mind opening up a PR?

**Comment by bubenkoff** [comment]
will try!

**Comment by novln** [comment]
@Pallinder What prevent the merge of #26?
