### ISSUE TITLE
Random number is repeated

### ISSUE THREAD

**Issue by panjunjie** [Pallinder/go-randomdata#33]
生成的随机数，重复的几率很大。

**Comment by Pallinder** [comment]
You are going to have to repeat the content of this message in English.

**Comment by Pallinder** [comment]
A PR would be nice

**Comment by Pallinder** [comment]
Closing this since discussion seems dead.

**Comment by noneymous** [comment]
Hi,

I've seen you are using math/rand, which causes diversity and gender quota issues ;-) 

- I (very) often ended up with the same gender
- I (unlikely) often had collisions, with the same names being chosen in a row

I suggest changing random number generation from
```
		g := rand.Intn(2)
```
to 
```
		n, _ := rand.Int(rand.Reader, big.NewInt(2))
		g := int(n.Int64())
```

I could mitigate the gender selection by generating the random number by myself, but the name for that gender is still decided by internals and not properly random.

**Comment by noneymous** [comment]
@Pallinder
