### ISSUE TITLE
Low variety output of randomdata.Paragraph()

### ISSUE THREAD

**Issue by hubyhuby** [Pallinder/go-randomdata#35]
randomdata.Paragraph()
Seems to output very often almost the same sentance .
It would be good if we could have a bigger variety.

For example when testing big data , with full text search,  having more words to scan would be nice

**Comment by Pallinder** [comment]
Agree wit this one. Will add some more paragraphs. Will most likely separate it out into a new json that contains only paragraphs (and quite a few of them)

**Comment by ericfialkowski** [comment]
I am working on a change that will help with this.

**Comment by Pallinder** [comment]
Fixed in #45
