### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by romshark** [Pallinder/go-randomdata#48]
It's kinda odd to see a cool library still not being versioned even though it seems to have been around for 5 years already and going through a decent evolution.

Please consider:
- Following [semantic versioning](https://semver.org/)
- Defining version tags in the [releases section](https://github.com/Pallinder/go-randomdata/releases)
- Recording a [change log](https://keepachangelog.com/de/1.0.0/) in both the [releases section](https://github.com/Pallinder/go-randomdata/releases) and a separate `CHANGELOG.md` file

This would greatly improve the library user experience and the seriousness of the project by allowing the user to achieve reproducible builds when using [dep](https://github.com/golang/dep) for example. 

Currently, there seems to be no guarantee on backward-compatibility so the current release would need to start with `0.1` according to [semver](https://semver.org/), though if it's already production ready then start with `1.0` right away.

This issue is loosely related to #47

**Comment by Pallinder** [comment]
Looks like I'll have some time for this one. Will get to this before merging the PR:s

**Comment by Pallinder** [comment]
Merged in https://github.com/Pallinder/go-randomdata/commit/422dd1e6304afe1161701ade6f7a873f3dc57679
