### ISSUE TITLE
Ability to seed the random generator

### ISSUE THREAD

**Issue by kernel-panic96** [Pallinder/go-randomdata#67]
If someone uses this in tests, the inability to seed the random number generator will cause unreproducible test flakiness.

**Comment by davidporos92** [comment]
I think it is possible by calling the following function with a seeded rand:

https://github.com/Pallinder/go-randomdata/blob/26f4a641b55b152ed383ba02b30b99763401ade3/random_data.go#L102-L104

**Comment by Pallinder** [comment]
Closing this one (see above)
